name: pcec
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter=1.0.0
  - pip=21.3.1
  - root=6.22.8
  - root-binaries=6.22.8
  - root-dependencies=6.22.8
  - pip:
    - scipy
    - tensorflow==2.5.0
    - pandas
    - scikit-learn
    - matplotlib
    - numpy
    - seaborn
    - tqdm
    - xgboost
    - hyperopt
    - opentsne
